### ISSUE TITLE
Small issue with splash

### ISSUE THREAD

**Issue by jaafit** [amigobrewbrew/polytopiacalculatorfirebase-public#1]
Hello, I found your app just now looking for a replacement for calc.polytopia.win (which has outdated stats now). I really like your interface and appreciate the full roster here.  You even have splash!  Which most calcs don't.   

But I wanted to let you know that the splash damage amt you have here is too high.  I know it says 2.5 in the wiki.  Well the wiki is wrong.  It's more like 2.33.  I'm not sure exactly, but 2.33 seems to be more accurate.  Another calculator on discord is using 2.25 which is too low.  You can test this most easily on units with defense of 1.  For example, an archer with 8 health will just barely die.  

I was planning to fork this and make my own version if you don't mind.  Just for me and my team.  I don't know anything about firebase though.  Can you tell me if that's required?  I know React pretty well.  

Happy to share my code here too if you want to copy any changes I make.

**Comment by amigobrewbrew** [comment]
Hi, happy you like it and thank you for your correction. I have updated the code and redeployed. Yes please be free to fork this code. I also created a dev branch in the case you would like to update the repo via a pull request. No real experience with collaboration like that though. So please let me know if you require something else. 
I hosted it before on Azure, so Firebase is not necessary. There is no back end to run the calculator. Good luck!
